### ISSUE TITLE
Añadir integración continua para comprobación ortográfica

### ISSUE THREAD

**Issue by JJ** [germaaan/TFG#1]
Usando Test::Text

**Comment by germaaan** [comment]
@JJ a ver si puedes echarle también un vistazo a esto por si es que estoy haciendo algo mal, que me dice Travis que falla durante la instalación de las dependencias: https://travis-ci.org/germaaan/TFG

**Comment by JJ** [comment]
Te falta el cpanfile con los requisitos, tendría que tener require
'Test::Text'

El 25 de junio de 2015, 10:51, German Martinez notifications@github.com
escribió:

> @JJ https://github.com/JJ a ver si puedes echarle también un vistazo a
> esto por si es que estoy haciendo algo mal, que me dice Travis que falla
> durante la instalación de las dependencias:
> https://travis-ci.org/germaaan/TFG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/germaaan/TFG/issues/1#issuecomment-115168249.

## 

JJ

**Comment by JJ** [comment]
O algo como esto https://github.com/JJ/nyc-42-8/blob/master/.travis.yml

**Comment by germaaan** [comment]
Con el cpanfile añadido ya no da error de instalación, pero finaliza con error igualmente. ¿Quizás que no encuentra los archivos de LaTeX a comprobar?

**Comment by JJ** [comment]
Creo que sólo busca .md y txt. Habría quizás que cambiar el fuente...

El 25 de junio de 2015, 11:45, German Martinez notifications@github.com
escribió:

> Con el cpanfile añadido ya no da error de instalación, pero finaliza con
> error igualmente. ¿Quizás que no encuentra los archivos de LaTeX a
> comprobar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/germaaan/TFG/issues/1#issuecomment-115189833.

## 

JJ

**Comment by germaaan** [comment]
He cambiado el nombre de los directorios para que los que eran palabras en español sin acentuación no me las detecte como error.
