### ISSUE TITLE
Corregir el inglés

### ISSUE THREAD

**Issue by JJ** [germaaan/TFG#10]
El resumen traducido está un poco flojo. "It is intended" debería ser "Our intention is" o "We intend to". ya no he seguido revisando, pero alguien que tuviera un buen nivel de inglés debería echarle un vistazo.

**Comment by germaaan** [comment]
¿Lo de "flojo" es por el contenido, por la traducción o por ambos? Por mirar como mejorarla además de corregir la traducción.

**Comment by JJ** [comment]
Traducción.

**Comment by germaaan** [comment]
Ok.
