### ISSUE TITLE
Mencionar trabajo inicial

### ISSUE THREAD

**Issue by JJ** [germaaan/TFG#11]
Hablas de "inicialmente" pero deberías mencionar explícitamente a @torresj y el trabajo que hizo, para que quede claro cuál es tu aportación al mismo. No sé si @torresj publicó algo (un informe de final de beca o algo así), pero habría que citarlo o simplemente escribir (quizás entre los dos) un pequeño anexo que explique el estado inicial del portal para que se entienda major la estructura general y los cambios que se hicieron desde entonces.

**Comment by germaaan** [comment]
Claro, de ahí lo de inicialmente, porque exactamente no sé qué hizo quién ni qué hizo, pero que vamos, ningún problema en mencionarlo y explicar que fue el que inició el desarrollo del portal, aunque creo que yo al menos poco más podría añadir.

**Comment by JJ** [comment]
Lo hizo prácticamente todo él y alguna cosa más @oskyar

**Comment by torresj** [comment]
Pues si necesitas que ayude a redactar algo o lo que sea me dices

**Comment by germaaan** [comment]
Muchas gracias @torresj.

Si no te importa, ¿podrías escribir unos cuantos puntos con lo que desarrollaste durante el tiempo que estuviste trabajando en esto? He añadido este párrafo seguido de una lista al principio del capítulo de implementación.

El desarrollo del portal de transparencia fue iniciado por Jaime Torres Benavente, tambi ́en becario anteriormente en la Oficina de Software Libre de la Universidad de Granada que se encarg ́o de establecer las bases del proyecto:

**Comment by torresj** [comment]
El estado del proyecto cuando yo me fui era el siguiente si no recuerdo mal:

Opendata: utilizando el software libre CKAN para crear portales de datos,
se desarrollo opendata que no es más que una versión personalizada de este
software. La ventaja que tiene es que provee una API con la que crear,
borrar y consultar todos los datos almacenados.

Transparente.ugr.es: El portal de transparente es una aplicación web basada
en node.js. Usa el framework express y el motor de plantillas jade. Además
se usa una base de datos no relacional en mongoDB.

-Backend: En una base de datos almacenamos la información referente a cada
conjunto de datos que se muestra en el portal. Entre esos datos
almacenados, se encuentra la url para realizar una petición a la API de
ckan (opendata) para descargar las tablas (archivos CSV) o los pdfs. Se
realiza así para poder establecer que conjuntos de datos y tablas queremos
mostrar de las almacenadas en opendata.

-Frontend: En primer lugar se convirtió una plantilla institucional html de
la ugr al lenguaje de plantillas python "jade" y se publicó en github
https://github.com/oslugr/PlantillaNeutraUGR . Como el objetivo de
transparente es visualizar o descargar datos, a la plantilla se le pasa los
datos de las urls de ckan para, mediante una llamada ajax, descargar el
archivo csv. Una vez tenemos parseado el csv procedemos a mostrar todos los
datos. Para ello, por cada tabla tenemos la opción de descargar o de
visualizar. La visualización se hace abriendo una ventana modal y, tras
descargar el archivo csv con ajax, utilizamos la API de google "google
charts" para mostrar una tabla que rellenamos con los valores del csv.

Más o menos , yendo al bulto, así dejé el proyecto. Si hablamos a nivel
general, todo esto tenía unos pasos previos que consistían en que Oscar
extraía los datos mediante scraping y Mónica creaba, subía y catalogaba
todos los datos.

Una vez terminaron mis 6 meses en la oficina, @oskyar siguió algunas
semanas más con el proyecto. El debería decirte que cosas hizo pero estoy
seguro que como mínimo, cambio el diseño de algunas partes de la página
para modernizar un poco el aspecto ya que la plantilla neutra era un poco
"cutre".

No se si necesitas una explicación más técnica o cualquier otro tipo de
dato. Cualquier cosa en la que pueda ayudarte solo dímelo.

**Comment by germaaan** [comment]
Ok, pues lo pongo en el proyecto, si la verdad es que con tan poco antelación de aviso, tampoco voy a pedirte que redactes mucho más, además que lo entregaré en un par de horas. En cualquier caso muchas gracias por todo.

**Comment by oskyar** [comment]
Siento no responder antes, tengo mil correos sin ver y no me había dado
cuenta, aunque tampoco pasa nada que no me menciones, lo que es la
estructura y todo lo hizo @torresj, yo solo modifiqué los estilos en la
primera quincena de Septiembre (y mi última quincena) para dejarlo
visualmente más bonito. Y refactoricé algo de código. Así que, todo OK.

¡Espero que te vaya genial Germán!
Un abrazo.

**Comment by germaaan** [comment]
Tranquilo, no pasa nada, si es que ha sido todo muy con las prisas, es normal.

Igualmente ya todo está terminado y entregado por fin!

Gracias de todas formas!
