### ISSUE TITLE
¡No uses Excel para los gráficos!

### ISSUE THREAD

**Issue by JJ** [germaaan/TFG#12]
Y menos la clásica captura de pantalla de Excel. Usa un programa serio como R y la librería ggplot2

**Comment by germaaan** [comment]
@JJ, ¿cómo puedo cambiar el orden de las barras en el gráfico? Es que las he introducido como 30, 50 y 100, pero me las muestra como 100, 30 y 50.

**Comment by JJ** [comment]
orden lexicográfico. Tienes que usar en R as.numeric

El 5 de julio de 2015, 11:11, German Martinez notifications@github.com
escribió:

> @JJ https://github.com/JJ, ¿cómo puedo cambiar el orden de las barras
> en el gráfico? Es que las he introducido como 30, 50 y 100, pero me las
> muestra como 100, 30 y 50.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/germaaan/TFG/issues/12#issuecomment-118599949.

## 

JJ

**Comment by germaaan** [comment]
Ok, gracias.
