### ISSUE TITLE
Revisión del TFG

### ISSUE THREAD

**Issue by germaaan** [germaaan/TFG#9]
@JJ cuando puedas échale un vistazo a esos capítulos y sácame todas las pegas que se te ocurran, please.

**Comment by JJ** [comment]
OK

2015-06-25 10:41 GMT+02:00 German Martinez notifications@github.com:

> Assigned #9 https://github.com/germaaan/TFG/issues/9 to @JJ
> https://github.com/JJ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/germaaan/TFG/issues/9#event-339802065.

## 

JJ

**Comment by germaaan** [comment]
Cierra con https://github.com/germaaan/TFG/commit/78667e15177d6f46102135f45d0e352c0916e13f
